### ISSUE TITLE
Lantern remains on wall after digging

### ISSUE THREAD

**Issue by AlexMooney** [Attnam/ivan#199] opened 2016-10-16 00:21 UTC
I dug from the lantern's position and even though the wall was destroyed, the lantern in still on the wall.  There is also a lantern with the lump of copper.

![image](https://cloud.githubusercontent.com/assets/8269566/19414266/e19fc7fe-9314-11e6-83ad-58d1d25eead3.png)

**Comment by emlai** [comment] 2016-10-16 00:30
Duplicate of #55

**Closed by emlai** 2016-10-16 00:30 UTC
