### ISSUE TITLE
game crashes when trying to run in full screen

### ISSUE THREAD

**Issue by L3gend** [Attnam/ivan#133] opened 2016-06-08 03:36 UTC
The latest version keeps crashing on me when I try to run it in full screen. It opens in a window fine. But once I try to put it in fullscreen either through the menu, or alt+enter, the game crashes. I'm using winxp sp3.  The same thing happens with version 505. But 504 runs in fullscreen no problem.

**Comment by andrewtweber** [comment] 2016-06-08 16:13
Thanks for the report! Closing as duplicate of #80

**Closed by andrewtweber** 2016-06-08 16:13 UTC
